#!/bin/bash

########################################################################
#                                                                      #
# file-size                                                            #
#                                                                      #
# Copyright (C) 2020 PJ Singh <psingh.cubic@gmail.com>                 #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# This file is part of Cubic - Custom Ubuntu ISO Creator.              #
#                                                                      #
# Cubic is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# Cubic is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the         #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Cubic. If not, see <http://www.gnu.org/licenses/>.        #
#                                                                      #
########################################################################

# Get the size of a file or directory in bytes for Cubic.

########################################################################
# Arguments
########################################################################

program=${0}
number_arguments=${#}
file_path=${1}

# echo "program..................... ${program}"
# echo "number of arguments......... ${number_arguments}"
# echo "file path................... ${file_path}"

########################################################################
# Command
########################################################################

# Do not echo the command because the output is parsed. The expected
# output format is: "<size>    <path>"

# du --block-size=1 --summarize --one-file-system "${file_path}"
du --block-size=1 --summarize "${file_path}"

